/*
 * Copyright (c) 2006-2021, RT-Thread Development Team
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Change Logs:
 * Date           Author       Notes
 * 2022-04-19     CGY       the first version
 */
#ifndef APPLICATIONS_AUTOPILOT_LIBRARIES_DRIVERLIB_COMPASSSENSOR_DL_COMPASSSENSOR_H_
#define APPLICATIONS_AUTOPILOT_LIBRARIES_DRIVERLIB_COMPASSSENSOR_DL_COMPASSSENSOR_H_



#endif /* APPLICATIONS_AUTOPILOT_LIBRARIES_DRIVERLIB_COMPASSSENSOR_DL_COMPASSSENSOR_H_ */
